# Generated by Django 3.2.9 on 2021-12-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('Embedded_link', models.CharField(max_length=1000, unique=True)),
                ('update_date', models.DateTimeField()),
            ],
        ),
    ]
