# Generated by Django 3.2.9 on 2021-12-03 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uservices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vids',
            old_name='update_date',
            new_name='Date_taken',
        ),
    ]
