# Generated by Django 3.2.9 on 2021-12-03 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Uservices', '0002_rename_update_date_vids_date_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='vids',
            name='iclass',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
